theme: jekyll-theme-cayman
title: Python para estudantes de Física - O mínimo necessário
description: Operações, tipos e variáveis. Controle de fluxo. Coleções: lists, tuples, sets e dictionaries. Funções. Classes.
